### Get custumers
GET localhost:8080/customer

### Get
GET localhost:8080/customer/2

### Get
GET localhost:8080/customer?name=Jessica

### Cadastra um customer
POST localhost:8080/customer
Content-Type: application/json

{
  "name": "Jessica",
  "email": "jessica@gmail.com"
}

### Cadastra um book
POST localhost:8080/book
Content-Type: application/json

{
  "name": "Livro 10",
  "price": 10.00,
  "customer_id": 1
}

### Update
PUT localhost:8080/customer/1
Content-Type: application/json

{
  "name": "Teste",
  "email": "teste@gmail.com"
}


### Exclui o usuário
DELETE localhost:8080/customer/2

### Get books
GET localhost:8080/book

### Get book paginacao
GET localhost:8080/book?size=2

### Get book ativo
GET localhost:8080/book/active

### Get book ativo paginacao
GET localhost:8080/book/active?size=1

### Get book ID
GET localhost:8080/book/20

### Exclui o book
DELETE localhost:8080/book/1

### Update book
PUT localhost:8080/book/1
Content-Type: application/json

{
  "name": "Livro 22",
  "price": 22.00
}